## config.toml
[window]
# width = 1280
# height = 720
width = 1440
height = 900
title = "Network Editor"
output_height = 250
preview_width = 400
sidebar_width = 300
gate_editor_open = false
output_open = true
warn_on_base_edit = true

[paths]
base_folder = "C-MCPN/base"
gates_folder = "C-MCPN/gates"
networks_folder = "C-MCPN/networks"
snapshots_folder = "app/snapshots"
output_scripts_folder = "app/output_scripts"
output_interpreter_folder = "C-MCPN/tools"

[defaults]
DEFAULT_GATES = ["INPUT", "OUTPUT", "AND", "OR", "NOT", "XOR", "NAND"]

[clingo]
max_solutions = 1
timeout = 1000
extra_files = []

[extra]
default_to_formatted_output = false
